image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements.txt

static-analysis:
  stage: test
  script:
    - echo "Running pylint"
    - pylint release-notes-generator.py